version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ../.env
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginxConfig/default.conf:/etc/nginx/conf.d/default.conf