version: '3'

services:
  frontend:
    image: ghcr.io/sergiusv/reactivitiesfront-image:latest
    restart: always
    ports:
      - "80:80"
    env_file:
      - ../.env
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf