name: 'build and deploy test server'
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  build-backend:
    name: 'Build Backend and Publish'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - id: owner_to_lower_case_owner
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: "Build&Deploy backend"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner_to_lower_case_owner.outputs.lowercase }}/reactivities-image:latest
  build-frontend:
    name: 'Build frontend and publish'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
        
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - id: owner_to_lower_case_owner
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: "Build&Deploy frontend"
        uses: docker/build-push-action@v2
        with:
          context: client-app
          file: client-app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.owner_to_lower_case_owner.outputs.lowercase }}/reactivitiesfront-image:latest
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: "Run deploy on server"
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.PRODUCTION_HOST }}
  #         username: ${{ secrets.PRODUCTION_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script_stop: true
  #         script: |
  #           cd ./my_project/folder
  #           sudo docker-compose down
  #           sudo docker-compose pull
  #           sudo docker-compose up -d
  #           sudo docker rmi $(docker images -f dangling=true -q)
  #           sudo docker system prune -a